service: default
runtime: nodejs10
instance_class: F4_1G

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
  - url: /(.*)/
    static_files: build/\1/index.html
    upload: build/(.*)/index.html
    secure: always
  - url: /static
    static_dir: build/static
    secure: always
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.8